### PR TITLE
Image gallery quick fixes

### LINKED ISSUE #777: Image gallery - The quick fix edition
Below is a series of edits we could implement in order to improve what we currently have.

**1. Container spacing:**
Add more spacing to the end of the text and start of the images. Beginning of white wobbly container is still in good spot, that should overlap with text. Make space 90px
screen shot 2017-04-11 at 10 56 11

------------------------------------------------------------------------------

**2. Arrow position**
Place arrows in right edge, inset within the image container area, rather than below the caption area. (Separated by 18px)
(Extra. Currently the arrow button turns grey (and stays) when clicked on. Grey should only happen upon hover/click. This is happening across all breakpoints)
screen shot 2017-04-11 at 11 16 00

------------------------------------------------------------------------------

**3. Image caption area**
No matter what the image width, stretch the caption to fit 7 columns wide. Hide the caption for the next/previous images.
screen shot 2017-04-11 at 11 15 07

------------------------------------------------------------------------------

**4. Image opacity**
Increase opacity of images not highlighted to 50%

------------------------------------------------------------------------------

**5. Gallery space**
Seems like on mobile, the first image in the gallery, determines the height of the gallery area? We should determine a set height for the image area, across all breakpoints. A consistent are which allows for image and caption to be seen at all times.
screen shot 2017-04-11 at 11 25 06 copy

------------------------------------------------------------------------------

**6. Image clicking**
Make next and previous images clickable along with arrow buttons

------------------------------------------------------------------------------

**7. Image numbering**
Add number indicator below the images and arrow buttons. This will help people identify how many images there are and that you can interact with the component.
screen shot 2017-04-11 at 11 40 31

### PR DESCRIPTION
**Pull request by davidpmccormick**
## What is this PR trying to achieve?
Addressing 'quick fixes' to image gallery. Closes #777.

## What does it look like?
- One caption visible at a time,
- Control buttons moved over (and to the right of) images
- 50% opacity non-selected images
- Clicking image moves to that image
screen shot 2017-04-19 at 13 07 54

- Cream slide background
- Slides bottom-aligned with background
screen shot 2017-04-19 at 13 08 31

## For interface components
- [x] Browser testing - Have you checked the component in our supported browsers
- [x] No javascript - Have you checked the component with javascript disabled
- [x] A11y testing - Have you run pa11y against the component and fixed/verified all errors, warnings and notices?

### CODE REVIEW

File: client/js/components/content-slider.js [hunk 1]
```diff
@@ -365,6 +364,14 @@ const contentSlider = (el, options) => {
   sliderElements.prevControl.addEventListener('click', prevSlide, true);
   sliderElements.nextControl.addEventListener('click', nextSlide, true);
 
+  nodeList(sliderElements.slideItems).forEach((item) => {
+    item.addEventListener('click', ({ target, currentTarget }) => {
+      if (!target.matches('img')) return;
```
Comment (jamesgorrie) [inline client/js/components/content-slider.js]: When is this the case?

File: client/scss/components/_captioned_image.scss [hunk 2]
```diff
@@ -86,6 +86,12 @@
   /* stylelint-enable plugin/selector-bem-pattern */
 }
 
+.captioned-image__number {
+  @include font('HNM5');
+  display: inline-block;
+  border-right: 1px solid color('keyline-grey');
```
Comment (jamesgorrie) [inline client/scss/components/_captioned_image.scss]: I thought we had changed these colours?

File: client/scss/components/_captioned_image.scss [hunk 3]
```diff
@@ -119,6 +125,10 @@
   &:focus {
     text-decoration: underline;
   }
+
+  &.captioned-image__truncate-control--is-hidden {
+    display: none;
```
Comment (jamesgorrie) [inline client/scss/components/_captioned_image.scss]: Why not have a generic hidden class?

File: client/scss/components/_image_gallery.scss [hunk 4]
```diff
@@ -120,38 +123,44 @@
...
-    justify-content: center;
-    background: color('smoke');
+    justify-content: flex-end;
+    background: color('cream');
+  }
+
+  .captioned-image__caption {
+    position: relative;
+    opacity: 0;
+    z-index: 0;
```
Comment (jamesgorrie) [inline client/scss/components/_image_gallery.scss]: Does this make the text un-selectable?

File: client/js/components/content-slider.js (hunk 1 above)
Comment (davidpmccormick) [inline client/js/components/content-slider.js]: The captions are part of the elements as well (and we require clicking the +more button to perform a separate function).

File: client/scss/components/_captioned_image.scss (hunk 2 above)
Comment (davidpmccormick) [inline client/scss/components/_captioned_image.scss]: Still in an unmerged PR – we should get it in sooner rather than later, though.

File: client/scss/components/_image_gallery.scss (hunk 4 above)
Comment (davidpmccormick) [inline client/scss/components/_image_gallery.scss]: Yes – without it, a transparent, but higher-up-in-the-source-order element could prevent the correct '+more' control from being clicked.

File: client/scss/components/_captioned_image.scss (hunk 3 above)
Comment (davidpmccormick) [inline client/scss/components/_captioned_image.scss]: I think we eschewed `is-hidden` early-doors in favour of per-component, BEM-y selectors. Maybe we've changed our minds?

File: client/js/components/content-slider.js (hunk 1 above)
Comment (jamesgorrie) [inline client/js/components/content-slider.js]: It feels like we should be adding the event listener to the element that we want no?
Either way, this works, but if we keep it, maybe make a note of why?

File: client/scss/components/_captioned_image.scss (hunk 2 above)
Comment (jamesgorrie) [inline client/scss/components/_captioned_image.scss]: It's approved - do you want to merge it?

File: client/scss/components/_captioned_image.scss (hunk 3 above)
Comment (jamesgorrie) [inline client/scss/components/_captioned_image.scss]: I'm happy for a generic one, less code really.

File: client/js/components/content-slider.js (hunk 1 above)
Comment (davidpmccormick) [inline client/js/components/content-slider.js]: Will add a note (because we want to get the data-attribute from the slide item).

File: client/scss/components/_captioned_image.scss (hunk 2 above)
Comment (davidpmccormick) [inline client/scss/components/_captioned_image.scss]: I'll merge colours first, yeah, then fix this one up.

File: client/scss/components/_captioned_image.scss (hunk 3 above)
Comment (davidpmccormick) [inline client/scss/components/_captioned_image.scss]: 🆒
