### PR TITLE
use display none to hide download options

### LINKED ISSUE #4584: View controls not working on mobile devices
The zoom in/out and rotate controls are disabled. Also, the previous/next page controls inadvertently download PDF file which consumes huge mobile data.

The dashboard has shown an unusual increase in 'download'. So I assume our users are accidentally downloading the PDF file instead of paginating.

### PR DESCRIPTION
**Pull request by gestchild**
fixes #4584

### CODE REVIEW

File: catalogue/webapp/components/Download/ViewerDownload.js [hunk 1]
```diff
@@ -23,17 +23,12 @@ const DownloadOptions = styled.div.attrs(props => ({
...
-  transition: opacity 400ms;
+  display: none;
   position: absolute;
   top: calc(100% + ${props => `${props.theme.spacingUnit * 2}px`});
   right: 0;
-  ${props =>
-    props.show &&
-    `z-index: 1;
-     opacity: 1;`}
+  ${props => props.show && `display: block;`}
```
Comment (davidpmccormick) [inline catalogue/webapp/components/Download/ViewerDownload.js]: Would keeping the `display` logic together be neater?

```
display: ${props => props.show ? 'block' : 'none'}
```
