### PR TITLE
Whats on bug

### LINKED ISSUE #4389: What's on month picker
An event that happens on multiple dates, which span more than one month, is not showing under each month on which it occurs .

### PR DESCRIPTION
**Pull request by gestchild**
fixes #4389, which is still useful before removing the date picker

### CODE REVIEW

File: common/utils/dates.js [hunk 1]
```diff
@@ -11,8 +11,8 @@ export function getEarliestFutureDateRange(
     .sort((a, b) => a.start - b.start)
     .find(
       range =>
-        london(range.start).isSameOrAfter(fromDate, 'day') &&
-        london(range.start).isSameOrAfter(london(), 'day')
+        london(range.end).isSameOrAfter(fromDate, 'day') &&
+        london(range.end).isSameOrAfter(london(), 'day')
```
Comment (jamesgorrie) [inline common/utils/dates.js]: Having a test for this might explain why this now works?
